apiVersion: v1
kind: ConfigMap
metadata:
  name: medic-config
  namespace: medic
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  TELEMEDICINE_PROVIDER: "JITSI"
  JITSI_BASE_URL: "https://meet.jit.si"
  SPRING_PROFILES_ACTIVE: "prod"
