apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthnet

resources:
  - namespace/namespace.yml
  - secrets/secrets.yml
  - configmaps/app-config.yml
  - deployments/patient-identity-service.yml
  - deployments/all-services.yml
  - services/services.yml
  - hpa/hpa.yml
